import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { db } from "@/lib/db";
import { apiHandler } from "@/lib/api-handler";

async function _GET(request: NextRequest) {
  const session = await auth();
  if (!session) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const role = (session.user as { role: string }).role;
  if (role !== "hr" && role !== "admin") {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  }

  const { searchParams } = new URL(request.url);
  const periodId = searchParams.get("period_id");

  if (!periodId) return NextResponse.json({ error: "period_id required" }, { status: 400 });

  const result = await db.execute({
    sql: `SELECT ps.*,
            e.name AS employee_name,
            e.type AS employee_type,
            e.department AS employee_department
          FROM payslips ps
          JOIN employees e ON e.id = ps.employee_id
          WHERE ps.period_id = ?
          ORDER BY e.name`,
    args: [periodId],
  });

  return NextResponse.json(result.rows);
}

async function _DELETE(request: NextRequest) {
  const session = await auth();
  if (!session) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const role = (session.user as { role: string }).role;
  if (role !== "hr" && role !== "admin") {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  }

  const { searchParams } = new URL(request.url);
  const periodId = searchParams.get("period_id");

  if (periodId) {
    const countResult = await db.execute({
      sql: "SELECT COUNT(*) as count FROM payslips WHERE period_id = ?",
      args: [periodId],
    });
    const deleted = (countResult.rows[0] as unknown as { count: number }).count;

    await db.execute({ sql: "DELETE FROM payslips WHERE period_id = ?", args: [periodId] });

    // Reset period to open so payslips can be regenerated by re-locking
    await db.execute({
      sql: "UPDATE payroll_periods SET status = 'open', locked_at = NULL, locked_by = NULL WHERE id = ?",
      args: [periodId],
    });

    return NextResponse.json({ success: true, deleted });
  }

  const countResult = await db.execute("SELECT COUNT(*) as count FROM payslips");
  const deleted = (countResult.rows[0] as unknown as { count: number }).count;

  await db.execute("DELETE FROM payslips");

  return NextResponse.json({ success: true, deleted });
}

export const GET = apiHandler(_GET);
export const DELETE = apiHandler(_DELETE);
